/**
 * TLC counterexample trace parser and fixture generator.
 * Parses TLC .trace output and generates test cases that reproduce the counterexample.
 * Zero dependencies.
 */

import type { TlcTraceEntry } from './types.js';

/**
 * Parse a TLC counterexample trace string into structured entries.
 * Format: "State N: <predicate>" followed by "var = value" lines.
 */
export function parseTlcTrace(traceText: string): TlcTraceEntry[] {
  if (!traceText.trim()) return [];

  const entries: TlcTraceEntry[] = [];
  const stateBlocks = traceText.split(/^State /m).filter(s => s.trim());

  let violatedInvariant: string | undefined;
  const invMatch = traceText.match(/Invariant (\w+) is violated/);
  if (invMatch) {
    violatedInvariant = invMatch[1];
  }

  for (const block of stateBlocks) {
    const headerMatch = block.match(/^(\d+):/);
    if (!headerMatch) continue;

    const step = parseInt(headerMatch[1] ?? '0', 10);
    const lines = block.split('\n').slice(1);
    const state: Record<string, string> = {};

    for (const line of lines) {
      const eqMatch = line.match(/^\s*(\w+)\s*=\s*(.+)$/);
      if (eqMatch && eqMatch[1] && eqMatch[2]) {
        state[eqMatch[1]] = eqMatch[2].trim();
      }
    }

    if (violatedInvariant) {
      entries.push({ step, state, violatedInvariant });
    } else {
      entries.push({ step, state });
    }
  }

  return entries;
}

/**
 * Generate counterexample test fixtures from parsed TLC trace.
 */
export function generateCounterexampleFixtures(
  trace: TlcTraceEntry[],
  framework: 'tla' | 'lean' | 'pytest',
): string {
  if (trace.length === 0) return '// Empty trace — no counterexample to reproduce\n';

  const first = trace[0];
  const last = trace[trace.length - 1];
  if (!first || !last) return '// Empty trace — no counterexample to reproduce\n';

  const varNames = Object.keys(first.state);

  if (framework === 'tla') {
    return generateTlaFixture(trace, varNames, last);
  } else if (framework === 'lean') {
    return generateLeanFixture(trace, varNames);
  } else {
    return generatePytestFixture(trace, varNames, last);
  }
}

function generateTlaFixture(trace: TlcTraceEntry[], varNames: string[], lastEntry: TlcTraceEntry): string {
  const lines: string[] = [
    '---- MODULE CounterexampleTrace ----',
    '',
    'VARIABLES ' + varNames.join(', '),
    '',
    'Init ==',
  ];

  const first = trace[0];
  if (!first) return lines.join('\n');

  const initState = first.state;
  const initConj = varNames
    .map(v => `${v} = ${initState[v] ?? 'UNDEF'}`)
    .join(' /\\ ');
  lines.push(`  /\\ ${initConj}`);

  if (trace.length > 1) {
    lines.push('', 'Next ==');
    for (let i = 1; i < trace.length; i++) {
      const s = trace[i];
      if (!s) continue;
      const conj = varNames.map(v => `${v} = ${s.state[v] ?? 'UNDEF'}`).join(' /\\ ');
      lines.push(`  \\/ /\\ ${conj}`);
    }
  }

  if (lastEntry.violatedInvariant) {
    lines.push('', `---- INVARIANT ${lastEntry.violatedInvariant} ----`);
  }

  lines.push('', '====');
  return lines.join('\n');
}

function generateLeanFixture(trace: TlcTraceEntry[], varNames: string[]): string {
  const lines: string[] = [
    '/- Counterexample trace generated by srs-formalizer -/',
    '',
    'def counterexample : List (String × String) := [',
  ];

  for (const entry of trace) {
    for (const v of varNames) {
      lines.push(`  ("${v}", ${entry.state[v] ?? 'UNDEF'}),`);
    }
  }

  lines.push(']');
  lines.push('');
  lines.push('theorem counterexample_exists : counterexample ≠ [] := by decide');
  return lines.join('\n');
}

function generatePytestFixture(
  trace: TlcTraceEntry[],
  varNames: string[],
  lastEntry: TlcTraceEntry,
): string {
  const lines: string[] = [
    '"""Counterexample trace reproduced as pytest fixture"""',
    '',
    'import pytest',
    '',
    '',
    '@pytest.fixture',
    'def counterexample_trace():',
    '    return [',
  ];

  for (const entry of trace) {
    const stateObj = varNames
      .map(v => `"${v}": ${entry.state[v] ?? 'None'}`)
      .join(', ');
    lines.push(`        {"step": ${entry.step}, ${stateObj}},`);
  }

  lines.push('    ]');
  lines.push('');
  lines.push('');
  lines.push('def test_counterexample_trace(counterexample_trace):');
  lines.push('    """Verify that the counterexample trace violates the invariant."""');
  lines.push('    trace = counterexample_trace');
  lines.push(`    assert len(trace) == ${trace.length}`);

  if (lastEntry.violatedInvariant) {
    lines.push(`    # Violated invariant: ${lastEntry.violatedInvariant}`);
  }

  for (const v of varNames) {
    const lastVal = lastEntry.state[v] ?? 'None';
    lines.push(`    assert trace[-1]["${v}"] == ${lastVal}`);
  }

  return lines.join('\n');
}
